name: Build RustDesk for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "C:\Users\runneradmin\.cargo\bin" >> $GITHUB_PATH

    - name: Install Visual Studio Build Tools
      run: |
        choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Install VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        echo "VCPKG_ROOT=C:\vcpkg" >> $GITHUB_ENV
        echo "C:\vcpkg" >> $GITHUB_PATH

    - name: Clear VCPKG cache
      run: |
        Remove-Item -Recurse -Force C:\vcpkg\buildtrees -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force C:\vcpkg\packages -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force C:\vcpkg\installed -ErrorAction SilentlyContinue

    - name: Install VCPKG dependencies
      run: |
        .\vcpkg\vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static --clean-after-build
        .\vcpkg\vcpkg integrate install

    - name: Verify VCPKG installation
      run: |
        dir C:\vcpkg\installed\x64-windows-static\include
        dir C:\vcpkg\installed\x64-windows-static\include\opus
        dir C:\vcpkg\installed\x64-windows-static\lib

    - name: Build RustDesk
      env:
        VCPKG_ROOT: C:\vcpkg
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: target/release/rustdesk.exe