name: Build RustDesk for Windows with VCPKG

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "C:\Users\runneradmin\.cargo\bin" >> $GITHUB_PATH
    - name: Install VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        echo "VCPKG_ROOT=C:\vcpkg" >> $GITHUB_ENV
    - name: Install dependencies with VCPKG
      run: |
        .\vcpkg\vcpkg install libvpx libyuv opus
        .\vcpkg\vcpkg integrate install
    - name: Build RustDesk
      run: cargo build --release