name: Build RustDesk for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "C:\Users\runneradmin\.cargo\bin" >> $GITHUB_PATH

    - name: Install Visual Studio Build Tools
      run: |
        choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.Component.VC.v141.x86.x64"

    - name: Install CMake
      run: |
        choco install -y cmake

    - name: Install VCPKG
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        echo "VCPKG_ROOT=C:\vcpkg" >> $GITHUB_ENV
        echo "C:\vcpkg" >> $GITHUB_PATH

    - name: Verify VCPKG installation
      run: |
        dir C:\vcpkg
        .\vcpkg\vcpkg version
        .\vcpkg\vcpkg list

    - name: Remove VCPKG manifest and overlays
      run: |
        Remove-Item -Force D:\a\rustdesk\rustdesk\vcpkg.json -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force D:\a\rustdesk\rustdesk\res\vcpkg -ErrorAction SilentlyContinue

    - name: Clear VCPKG cache
      run: |
        Remove-Item -Recurse -Force C:\vcpkg\buildtrees -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force C:\vcpkg\packages -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force C:\vcpkg\installed -ErrorAction SilentlyContinue

    - name: Check available ports
      run: |
        .\vcpkg\vcpkg search libvpx
        .\vcpkg\vcpkg search libyuv
        .\vcpkg\vcpkg search opus
        dir C:\vcpkg\ports\libvpx || echo "libvpx port not found"
        dir C:\vcpkg\ports\libyuv || echo "libyuv port not found"
        dir C:\vcpkg\ports\opus || echo "opus port not found"

    - name: Install libvpx
      run: |
        .\vcpkg\vcpkg install libvpx:x64-windows-static --classic --debug --clean-after-build
        if (-not $?) { exit 1 }

    - name: Install libyuv
      run: |
        .\vcpkg\vcpkg install libyuv:x64-windows-static --classic --debug --clean-after-build
        if (-not $?) { exit 1 }

    - name: Install opus
      run: |
        .\vcpkg\vcpkg install opus:x64-windows-static --classic --debug --clean-after-build
        if (-not $?) { exit 1 }

    - name: Integrate VCPKG
      run: |
        .\vcpkg\vcpkg integrate install

    - name: Verify VCPKG installation
      run: |
        dir C:\vcpkg\installed || echo "Directory C:\vcpkg\installed not found"
        dir C:\vcpkg\installed\x64-windows-static || echo "Directory C:\vcpkg\installed\x64-windows-static not found"
        dir C:\vcpkg\installed\x64-windows-static\include || echo "Directory C:\vcpkg\installed\x64-windows-static\include not found"
        dir C:\vcpkg\installed\x64-windows-static\include\opus || echo "Directory C:\vcpkg\installed\x64-windows-static\include\opus not found"
        dir C:\vcpkg\installed\x64-windows-static\lib || echo "Directory C:\vcpkg\installed\x64-windows-static\lib not found"

    - name: Build RustDesk
      env:
        VCPKG_ROOT: C:\vcpkg
      run: cargo build --release

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: target/release/rustdesk.exe